name: Setup ONNX (Linux)
description: Compiles ONNX from source on Linux
inputs:
  onnx-tag:
    description: The Git tag or commit hash of ONNX to build
    required: true

runs:
  using: composite
  steps:
    - name: Define cache key
      id: cache-key
      shell: bash
      run: |
        echo "key=${{ format(
          'setup-onnx-{0}-{1}-{2}-{3}',
          runner.os,
          runner.arch,
          inputs.onnx-tag,
          hashFiles('.github/cmake-cache/onnx-base.cmake', '.github/cmake-cache/onnx-unix.cmake')
        ) }}" >> $GITHUB_OUTPUT

    - name: Restore ONNX
      id: cache-onnx
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: onnx-dist
        key: ${{ steps.cache-key.outputs.key }}

    - name: Checkout onnx
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        repository: onnx/onnx
        ref: ${{ inputs.onnx-tag }}
        path: onnx
        submodules: recursive

    - name: Configure ONNX
      shell: bash
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      run: cmake -S onnx -B build_onnx -G Ninja -LA
        -C "$GITHUB_WORKSPACE/.github/cmake-cache/onnx-base.cmake"
        -C "$GITHUB_WORKSPACE/.github/cmake-cache/onnx-unix.cmake"

    - name: Build onnx
      shell: bash
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      run: cmake --build build_onnx

    - name: Install ONNX
      shell: bash
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      run: cmake --install build_onnx --prefix onnx-dist

    - name: Save ONNX
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: onnx-dist
        key: ${{ steps.cache-key.outputs.key }}

    - name: Configure ONNX Path
      shell: bash
      run: |
        onnxRoot=$(realpath onnx-dist)
        echo "CMAKE_PREFIX_PATH=$onnxRoot${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$onnxRoot/lib:$onnxRoot/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" >> $GITHUB_ENV
