name: Publish

on:
  workflow_dispatch:
    inputs:
      artifact-pattern:
        description: Artifact name pattern to download
        type: string
        required: false
        default: "*"
      package:
        description: Package name being published
        type: string
        required: true
      packages-dir:
        description: Directory to publish from
        type: string
        required: false
        default: dist
      repository:
        description: Package index to publish to
        type: choice
        required: false
        default: testpypi
        options:
          - testpypi
          - pypi
      repository-url:
        description: Package index upload URL
        type: string
        required: false
        default: https://test.pypi.org/legacy/
      run-id:
        description: Workflow run id containing distribution artifacts
        type: string
        required: true

jobs:
  publish:
    name: Publish to ${{ inputs.repository == 'testpypi' && 'TestPyPI' || 'PyPI' }}
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.repository }}-${{ inputs.package }}
      url: ${{ inputs.repository == 'testpypi' && format('https://test.pypi.org/p/{0}', inputs.package) || format('https://pypi.org/p/{0}', inputs.package) }}

    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
      - name: Download distributions
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          pattern: ${{ inputs.artifact-pattern }}
          path: ${{ inputs.packages-dir }}
          merge-multiple: true
          run-id: ${{ inputs.run-id }}
          github-token: ${{ github.token }}

      - name: Publish distributions
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
        with:
          packages-dir: ${{ inputs.packages-dir }}
          repository-url: ${{ inputs.repository-url }}
